spring.profiles.active=sandbox

server.servlet.context-path=/api

### H2 - Persist H2 configs ###
spring.datasource.url=jdbc:h2:file:./h2/nchandi-h2-db
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view = false
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.settings.web-allow-others=true


### H2 - Use a SQL scrip file ###
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.datasource.url=jdbc:h2:mem:test
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.driver-class-name=org.h2.Driver
# spring.jpa.defer-datasource-initialization=true
# spring.jpa.open-in-view = false

### Persist a database - Old configs. ###
# spring.datasource.name=NCHANDI_WEBSITE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.initialize=false
# spring.datasource.url=jdbc:h2:file:~/Workspace/Development/h2/NCHANDI_WEBSITE;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;
# spring.jpa.hibernate.ddl-auto = update

### Logging ###
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.hibernate=ERROR
logging.file.path=logging
spring.output.ansi.enabled=always

### Messaging service ###
twilio.sid=AC05a2caba2fa3c6401fc32d5e5b2461a2
twilio.token=ece9e610f8cbc6cfd4a22aece0e065a5
twilio.phone="+18887805441"
twilio.notification.flow=FW9982c5731b7437af9f896977941d4fbf
twilio.feedback.flow=FW42726b6486962edc036085fc85b939ad

### Email service ###
zoho.username=technology@nchandi.org
zoho.password=12Steps!

### UI URLs - Comment out the production ui url when testing this spring-boot application locally ###
# ui.url=http://localhost:3000
ui.url=https://www.nchandi.org

