
CREATE SCHEMA NCHANDI

DROP TABLE IF EXISTS ADMIN;  
DROP TABLE IF EXISTS ARCHIVED_REPORT;  
DROP TABLE IF EXISTS FACILITY;  
DROP TABLE IF EXISTS GENERAL_RESOURCE;  
DROP TABLE IF EXISTS MEMBER;  
DROP TABLE IF EXISTS MONTHLY_REPORT;  
DROP TABLE IF EXISTS PANEL;  
DROP TABLE IF EXISTS PANEL_MATERIAL;  
DROP TABLE IF EXISTS PENDING;  

CREATE TABLE NCHANDI.ADMIN(
   ID VARCHAR (255),
   COMMITMENT VARCHAR (255),
   EMAIL  VARCHAR (255),
   FIRST_NAME  VARCHAR (255),
   LAST_NAME VARCHAR (255),
   PHONE VARCHAR (255),
   PREFFERED_CONTACT_METHOD VARCHAR (255)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.ARCHIVED_REPORT(
   ID VARCHAR (255),
   TITLE VARCHAR (255),
   URL  VARCHAR (255)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.FACILITY(
   ID VARCHAR (255),
   ACTIVE NUMBER(1,0) ,
   ADDRESS  VARCHAR (255),
   ALERNATE_CONTACT_EMAIL  VARCHAR (255),
   ALTERNATE_CONTACT_NAME VARCHAR (255),
   ALTERNATE_CONTACT_PHONE VARCHAR (255),
   CITY VARCHAR (255),
   FACILITY_NAME  VARCHAR (255),
   FACILITY_TYPE  VARCHAR (255),
   MAIN_CONTACT_EMAIL VARCHAR (255),
   MAIN_CONTACT_NAME VARCHAR (255),
   MAIN_CONTACT_PHONE  VARCHAR (255),
   STATE  VARCHAR (255),
   WEBSITE VARCHAR (255),
   ZIP VARCHAR (255)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.GENERAL_RESOURCE(
   ID VARCHAR (255),
   ORDER    NUMBER (10),
   TITLE  VARCHAR (255),
   URL  VARCHAR (255)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.MEMBER(
   ID VARCHAR (255),
   COMMITMENT VARCHAR (255),
   EMAIL  VARCHAR (255),
   FIRST_NAME  VARCHAR (255),
   LAST_NAME VARCHAR (255),
   PHONE VARCHAR (255),
   PREFFERED_CONTACT_METHOD VARCHAR (255)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.MONTHLY_REPORT(
   ID VARCHAR (255),
   IS_ARCHIVE NUMBER(1,0),
   MONTH NUMBER(10),
   TIMESTAMP  TIMESTAMP,
   TITLE VARCHAR (255),
   TYPE VARCHAR (255),
   URL VARCHAR (255)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.PANEL(
   ID VARCHAR (255),
   ACTIVE NUMBER(1,0),
   DAY_OF_WEEK VARCHAR (255),
   EVENT_TIME VARCHAR (255),
   GENDER NUMBER(10),
   LOCATION VARCHAR (255),
   MARK_AS_MEMBERS_NEEDED NUMBER(1,0),
   NUMBER_NEEDED NUMBER(10),
   REMINDER NUMBER(1,0),
   WEEK_OF_MONTH NUMBER(10),
   BOARD_CHAMPION_ID VARCHAR (255),
   FACILITY_ID VARCHAR (255),
   PANEL_COORDINATOR_ID VARCHAR (255),
   PANEL_LEADER_ID VARCHAR (255),
   PANEL_MEMBER_1_ID VARCHAR (255),
   PANEL_MEMBER_2_ID VARCHAR (255),
   PANEL_MEMBER_3_ID VARCHAR (255),
   PANEL_MEMBER_4_ID VARCHAR (255),
   PANEL_MEMBER_5_ID VARCHAR (255)
   CONSTRAINT fk_boardChampion_tbMember
    FOREIGN KEY (BOARD_CHAMPION_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_facility_tbMember
    FOREIGN KEY (FACILITY_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_panelCoordinator_tbMember
    FOREIGN KEY (PANEL_COORDINATOR_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_panelLeader_tbMember
    FOREIGN KEY (PANEL_LEADER_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_panelMember1_tbMember
    FOREIGN KEY (PANEL_MEMBER_1_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_panelMember2_tbMember
    FOREIGN KEY (PANEL_MEMBER_2_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_panelMember3_tbMember
    FOREIGN KEY (PANEL_MEMBER_3_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_panelMember4_tbMember
    FOREIGN KEY (PANEL_MEMBER_4_ID)
    REFERENCES MEMBER (ID)
   CONSTRAINT fk_panelMember5_tbMember
    FOREIGN KEY (PANEL_MEMBER_5_ID)
    REFERENCES MEMBER (ID)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.PANEL_MATERIAL(
   ID VARCHAR (255),
   ORDER    NUMBER (10),
   TITLE  VARCHAR (255),
   URL  VARCHAR (255)
   PRIMARY KEY (ID)
);

CREATE TABLE NCHANDI.PENDING(
   ID VARCHAR (255),
   DAY_OF_WEEK  VARCHAR (255),
   EMAIL  VARCHAR (255),
   EVENT_TIME  VARCHAR (255),
   FACILITY_NAME VARCHAR (255),
   FIRST_NAME VARCHAR (255),
   LAST_NAME VARCHAR (255),
   PANEL_ID  VARCHAR (255),
   PHONE  VARCHAR (255),
   PREFERRED_CONTACT_METHOD VARCHAR (255),
   WEEK_OF_MONTH VARCHAR (255)
   PRIMARY KEY (ID)
);