
CREATE SCHEMA IF NOT EXISTS NCHANDI_WEBSITE;

-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.ADMIN;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.ARCHIVED_REPORT;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.FACILITY;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.GENERAL_RESOURCE;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.MEMBER;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.MONTHLY_REPORT;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.PANEL;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.PANEL_MATERIAL;  
-- DROP TABLE IF EXISTS NCHANDI_WEBSITE.PENDING;  

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.ADMIN(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    COMMITMENT VARCHAR (255),
--    EMAIL  VARCHAR (255),
--    FIRST_NAME  VARCHAR (255),
--    LAST_NAME VARCHAR (255),
--    PHONE VARCHAR (255),
--    PREFFERED_CONTACT_METHOD VARCHAR (255)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.ARCHIVED_REPORT(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    TITLE VARCHAR (255),
--    URL  VARCHAR (255)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.FACILITY(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    ACTIVE NUMBER(1,0) ,
--    ADDRESS  VARCHAR (255),
--    ALERNATE_CONTACT_EMAIL  VARCHAR (255),
--    ALTERNATE_CONTACT_NAME VARCHAR (255),
--    ALTERNATE_CONTACT_PHONE VARCHAR (255),
--    CITY VARCHAR (255),
--    FACILITY_NAME  VARCHAR (255),
--    FACILITY_TYPE  VARCHAR (255),
--    MAIN_CONTACT_EMAIL VARCHAR (255),
--    MAIN_CONTACT_NAME VARCHAR (255),
--    MAIN_CONTACT_PHONE  VARCHAR (255),
--    STATE  VARCHAR (255),
--    WEBSITE VARCHAR (255),
--    ZIP VARCHAR (255)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.GENERAL_RESOURCE(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    THE_ORDER    NUMBER (10),
--    TITLE  VARCHAR (255),
--    URL  VARCHAR (255)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.MEMBER(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    COMMITMENT VARCHAR (255),
--    EMAIL  VARCHAR (255),
--    FIRST_NAME  VARCHAR (255),
--    LAST_NAME VARCHAR (255),
--    PHONE VARCHAR (255),
--    PREFFERED_CONTACT_METHOD VARCHAR (255)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.MONTHLY_REPORT(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    IS_ARCHIVE NUMBER(1,0),
--    MONTH_OF_YEAR NUMBER(10),
--    TIMESTAMP  TIMESTAMP,
--    TITLE VARCHAR (255),
--    TYPE_OF_REPORT VARCHAR (255),
--    URL VARCHAR (255)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.PANEL(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    ACTIVE NUMBER(1,0),
--    DAY_OF_WEEK VARCHAR (255),
--    EVENT_TIME VARCHAR (255),
--    GENDER NUMBER(10),
--    LOCATION VARCHAR (255),
--    MARK_AS_MEMBERS_NEEDED NUMBER(1,0),
--    NUMBER_NEEDED NUMBER(10),
--    REMINDER NUMBER(1,0),
--    WEEK_OF_MONTH NUMBER(10),
--    BOARD_CHAMPION_ID VARCHAR (255) REFERENCES MEMBER (ID),
--    FACILITY_ID VARCHAR (255) REFERENCES FACILITY (ID),
--    PANEL_COORDINATOR_ID VARCHAR (255) REFERENCES MEMBER (ID),
--    PANEL_LEADER_ID VARCHAR (255) REFERENCES MEMBER (ID),
--    PANEL_MEMBER_1_ID VARCHAR (255) REFERENCES MEMBER (ID),
--    PANEL_MEMBER_2_ID VARCHAR (255) REFERENCES MEMBER (ID),
--    PANEL_MEMBER_3_ID VARCHAR (255) REFERENCES MEMBER (ID),
--    PANEL_MEMBER_4_ID VARCHAR (255) REFERENCES MEMBER (ID),
--    PANEL_MEMBER_5_ID VARCHAR (255) REFERENCES MEMBER (ID)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.PANEL_MATERIAL(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    THE_ORDER    NUMBER (10),
--    TITLE  VARCHAR (255),
--    URL  VARCHAR (255)
-- );

-- CREATE TABLE IF NOT EXISTS NCHANDI_WEBSITE.PENDING(
--    ID VARCHAR AUTO_INCREMENT  PRIMARY KEY,
--    DAY_OF_WEEK  VARCHAR (255),
--    EMAIL  VARCHAR (255),
--    EVENT_TIME  VARCHAR (255),
--    FACILITY_NAME VARCHAR (255),
--    FIRST_NAME VARCHAR (255),
--    LAST_NAME VARCHAR (255),
--    PANEL_ID  VARCHAR (255),
--    PHONE  VARCHAR (255),
--    PREFERRED_CONTACT_METHOD VARCHAR (255),
--    WEEK_OF_MONTH VARCHAR (255)
-- );